
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TkFalse = 46;
  public static final int TkBoolean = 32;
  public static final int TkPrint = 44;
  public static final int TkNegacion = 13;
  public static final int TkTrue = 45;
  public static final int TkComa = 2;
  public static final int TkDesigual = 19;
  public static final int TkRotacion = 22;
  public static final int TkMas = 6;
  public static final int TkDone = 40;
  public static final int TkTrasposicion = 23;
  public static final int TkIf = 34;
  public static final int TkFrom = 39;
  public static final int TkUsing = 27;
  public static final int TkAsignacion = 24;
  public static final int TkParAbre = 4;
  public static final int TkRead = 43;
  public static final int TkPuntoYComa = 3;
  public static final int TkThen = 35;
  public static final int TkIgual = 18;
  public static final int TkConjuncion = 11;
  public static final int EOF = 0;
  public static final int TkBegin = 29;
  public static final int TkCanvas = 33;
  public static final int TkTo = 38;
  public static final int TkDisyuncion = 12;
  public static final int error = 1;
  public static final int TkNumLit = 25;
  public static final int TkOfType = 28;
  public static final int TkDiv = 9;
  public static final int TkCanvasLit = 26;
  public static final int TkMenos = 7;
  public static final int TkMenor = 14;
  public static final int TkMult = 8;
  public static final int TkWith = 42;
  public static final int TkIdent = 47;
  public static final int TkMenorIgual = 15;
  public static final int TkError = 48;
  public static final int TkInteger = 31;
  public static final int TkParCierra = 5;
  public static final int TkMod = 10;
  public static final int TkMayor = 16;
  public static final int TkConcatVertical = 21;
  public static final int TkMayorIgual = 17;
  public static final int TkWhile = 37;
  public static final int TkOtherwise = 36;
  public static final int TkConcatHorizontal = 20;
  public static final int TkRepeat = 41;
  public static final int TkEnd = 30;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TkComa",
  "TkPuntoYComa",
  "TkParAbre",
  "TkParCierra",
  "TkMas",
  "TkMenos",
  "TkMult",
  "TkDiv",
  "TkMod",
  "TkConjuncion",
  "TkDisyuncion",
  "TkNegacion",
  "TkMenor",
  "TkMenorIgual",
  "TkMayor",
  "TkMayorIgual",
  "TkIgual",
  "TkDesigual",
  "TkConcatHorizontal",
  "TkConcatVertical",
  "TkRotacion",
  "TkTrasposicion",
  "TkAsignacion",
  "TkNumLit",
  "TkCanvasLit",
  "TkUsing",
  "TkOfType",
  "TkBegin",
  "TkEnd",
  "TkInteger",
  "TkBoolean",
  "TkCanvas",
  "TkIf",
  "TkThen",
  "TkOtherwise",
  "TkWhile",
  "TkTo",
  "TkFrom",
  "TkDone",
  "TkRepeat",
  "TkWith",
  "TkRead",
  "TkPrint",
  "TkTrue",
  "TkFalse",
  "TkIdent",
  "TkError"
  };
}

